### ISSUE TITLE
Backup DB

### ISSUE THREAD

**Issue by RogerTangos** [bank-green/bankgreen-django#50]
AS A Bank.Green Developer
I WANT periodic backups of the data.bank.green data
SO THAT if we need to roll back due to ransomware, we can

**Acceptance criteria**
- sqlite.db is periodically copied to another directory
- the new file is timestamped
- the new file has restricted permissions

**Comment by shuesken** [comment]
Running via a cronjob executing `/home/django/backup.sh` daily.
