### ISSUE TITLE
sustainable banks comparison bugs

### ISSUE THREAD

**Issue by shuesken** [bank-green/bankgreen-django#63]
On https://test.bank.green, the new Features version is running. I uncovered a few bugs in comparing https://bank.green/sustainable-ethical-banks with https://test.bank.green/sustainable-ethical-banks

There are two bugs on the live site: "Checking & Savings Accounts" is always displayed as false because it was forgotten in the GraphQL query; "Mortgage or Loan Options" is always displayed as false because of a typo in the display code. Both are addressed by the test.bank.green branch.

On the new site, "Free Checking Account Available" is always false because in the backend migration, `free_checking` only ever got initialized as `offered=FeatureAvailabilityChoice.MAYBE` – @RogerTangos , why?

"Free International Card Payments" is also always false because of a mistake in the display code – the feature is called `international_card_payments` rather than `free_international_card_payments`. @RogerTangos , why?

**Comment by RogerTangos** [comment]
* **Checking & Savings Accounts** has been migrated to two fields, `checking` and `saving`. They should both be set toto `YES`if the original data showed yes. Can the frontend handle this?
* **`free_checking`** is updated in a PR
* **`free_international_card_payments`** is updated using the UI on the admin site. I think it should work now.

I'm not sure what action needs to be taken on **Mortgage or Loan Options**. Is that purely something that needs to be changed in the frontend, or does it need to be changed in the backend too?

**Comment by shuesken** [comment]
all fixed
